context:
  name: beckhoff-ads
  version: "113.0.32-1"

recipe:
  name: ${{ name }}
  version: ${{ version }}.0.0

source:
  url: https://github.com/Beckhoff/ADS/archive/refs/tags/${{ version }}.tar.gz
  sha256: c48110f4f1bd910809c90f2f4275eee658a26cbbbc544a981a1ebd53facebfd5
  patches:
    # meson.build on v22 does not provide install directives - add them via patch. To be checked for newer versions.
    - meson-build.patch

build:
  number: 0
  skip:
    - win
  script: |
    meson setup build --prefix="$PREFIX" -Dlibdir="$PREFIX/lib" -Dwerror=false
    ninja -C build install

outputs:
  - package:
      name: ${{ name }}
    requirements:
      build:
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - meson
        - ninja
      run_exports:
        - ${{ pin_subpackage(name, upper_bound='x.x.x') }}
    build:
      files:
        - include
        - bin
        - if: linux
          then:
            - lib/*.so*
        - if: osx
          then:
            - lib/*.dylib*
        - lib/pkgconfig
    tests:
      - script:
          - test -d "${PREFIX}/include/AdsLib"
          - test -f "${PREFIX}/include/AdsLib/AdsLib.h"
          - if: linux
            then:
              - test -f "${PREFIX}/lib/libAdsLib.so"
          - if: osx
            then:
              - test -f "${PREFIX}/lib/libAdsLib.dylib"
          - adstool --help

  - package:
      name: ${{ name }}-static
    requirements:
      build:
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - meson
        - ninja
    build:
      files:
        - lib/*.a
    tests:
      - script:
          - test -f "${PREFIX}/lib/libAdsLib.a"

about:
  homepage: https://github.com/Beckhoff/ADS
  license: MIT
  license_file: LICENSE
  summary: Beckhoff protocol to communicate with TwinCAT devices
  description: |
    This library is intended to provide easy use as ADS client applications running on non-windows systems 
    (e.g. FreeBSD, Linux, ...) to communicate with TwinCAT devices via TCP/IP.
  documentation: https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_ads_intro/index.html
  repository: https://github.com/Beckhoff/ADS

extra:
  recipe-maintainers:
    - AndreFavotto
    - mac-kan
    - javicereijo
