context:
  name: beckhoff-ads
  version: 25.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}.0

source:
  url: https://github.com/Beckhoff/ADS/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 38d11000001ee40a43e412ecd76efe3108ea110d43f618371e4ecaae6f251421

build:
  number: 0
  skip:
    - win
  script: |
    meson setup build --prefix="$PREFIX" -Dlibdir="$PREFIX/lib" -Dwerror=false
    ninja -C build install

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - meson
    - ninja

tests:
  - script:
      - test -d "${PREFIX}/include/AdsLib"
      - test -f "${PREFIX}/include/AdsLib/AdsLib.h"
      - adstool --help

about:
  homepage: https://github.com/Beckhoff/ADS
  license: MIT
  license_file: LICENSE
  summary: Beckhoff protocol to communicate with TwinCAT devices
  description: |
    This library is intended to provide easy use as ADS client applications running on non-windows systems 
    (e.g. FreeBSD, Linux, ...) to communicate with TwinCAT devices via TCP/IP.
  documentation: https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_ads_intro/index.html
  repository: https://github.com/Beckhoff/ADS

extra:
  recipe-maintainers:
    - AndreFavotto
    - mac-kan
    - javicereijo
